CREATE TABLE `accounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`type` enum('twitter','telegram','email') NOT NULL,
	`label` varchar(128) NOT NULL,
	`handle` varchar(255) NOT NULL,
	`credentials` json,
	`isActive` boolean NOT NULL DEFAULT true,
	`dailyLimit` int NOT NULL DEFAULT 50,
	`sentToday` int NOT NULL DEFAULT 0,
	`lastResetAt` timestamp DEFAULT (now()),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `accounts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `analytics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`date` varchar(16) NOT NULL,
	`projectsDiscovered` int NOT NULL DEFAULT 0,
	`projectsContacted` int NOT NULL DEFAULT 0,
	`projectsReplied` int NOT NULL DEFAULT 0,
	`projectsListed` int NOT NULL DEFAULT 0,
	`projectsRejected` int NOT NULL DEFAULT 0,
	`messagesSent` int NOT NULL DEFAULT 0,
	`messagesReceived` int NOT NULL DEFAULT 0,
	`followUpsSent` int NOT NULL DEFAULT 0,
	`listingFeeTotal` decimal(20,2) DEFAULT '0',
	`listingFeeCurrency` varchar(16) DEFAULT 'USDT',
	`replyRate` decimal(5,2) DEFAULT '0',
	`conversionRate` decimal(5,2) DEFAULT '0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `analytics_id` PRIMARY KEY(`id`),
	CONSTRAINT `analytics_date_unique` UNIQUE(`date`)
);
--> statement-breakpoint
CREATE TABLE `messages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`accountId` int,
	`templateId` int,
	`direction` enum('outbound','inbound') NOT NULL DEFAULT 'outbound',
	`channel` enum('twitter','telegram','email','discord','manual') NOT NULL,
	`subject` varchar(512),
	`bodyEn` text NOT NULL,
	`bodyCn` text,
	`status` enum('pending','sent','delivered','read','replied','failed','bounced') NOT NULL DEFAULT 'pending',
	`isFollowUp` boolean NOT NULL DEFAULT false,
	`followUpNumber` int NOT NULL DEFAULT 1,
	`replyIntent` varchar(64),
	`replysentiment` varchar(32),
	`llmSuggestion` text,
	`llmSuggestionCn` text,
	`scheduledAt` timestamp,
	`sentAt` timestamp,
	`readAt` timestamp,
	`repliedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `messages_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`symbol` varchar(32) NOT NULL,
	`slug` varchar(255),
	`description` text,
	`logoUrl` varchar(512),
	`source` enum('coinmarketcap','coingecko','manual') NOT NULL DEFAULT 'manual',
	`sourceId` varchar(128),
	`isMeme` boolean NOT NULL DEFAULT false,
	`category` varchar(128),
	`tags` json,
	`marketCap` decimal(20,2),
	`price` decimal(20,8),
	`volume24h` decimal(20,2),
	`rank` int,
	`chain` varchar(64),
	`contractAddress` varchar(255),
	`website` varchar(512),
	`twitterHandle` varchar(128),
	`twitterUrl` varchar(512),
	`telegramUrl` varchar(512),
	`discordUrl` varchar(512),
	`officialEmail` varchar(320),
	`contactPersonName` varchar(255),
	`contactPersonTg` varchar(128),
	`status` enum('discovered','contacted','replied','negotiating','listed','rejected','blacklisted') NOT NULL DEFAULT 'discovered',
	`priority` enum('high','medium','low') NOT NULL DEFAULT 'medium',
	`notes` text,
	`listingFee` decimal(20,2),
	`listingFeeCurrency` varchar(16),
	`listedOnSourceAt` timestamp,
	`firstContactAt` timestamp,
	`lastContactAt` timestamp,
	`lastReplyAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `projects_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`key` varchar(128) NOT NULL,
	`value` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `settings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`scenario` enum('first_contact','follow_up','quote','negotiation','closing') NOT NULL DEFAULT 'first_contact',
	`channel` enum('twitter','telegram','email','all') NOT NULL DEFAULT 'all',
	`subject` varchar(512),
	`bodyEn` text NOT NULL,
	`bodyCn` text,
	`variables` json,
	`isDefault` boolean NOT NULL DEFAULT false,
	`usageCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `templates_id` PRIMARY KEY(`id`)
);
